baseurl = "https://nicruo.com"
title = "nicruo"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

#disqusShortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[permalinks]
  [permalinks.page]
    posts = '/posts/:year/:month/:day/:slug/'
    tutorials = '/training/:slug/'

[params]
  author = "José da Cruz Medeiros"
  info = "DevOps, .NET and Development"
  description = "nicruo - Many things tech."
  keywords = "blog,developer,devops"
  #avatarurl = "images/avatar.jpg"
  gravatar = "nicruo@gmail.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2018

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/nicruo/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 2
  url = "https://twitter.com/nicruo/"
[[params.social]]
  name = "Mastodon"
  icon = "fa fa-mastodon fa-2x"
  weight = 3
  url = "https://hachyderm.io/@nicruo"
[[params.social]]
  name = "Email"
  icon = "fa fa-envelope fa-2x"
  weight = 4
  url = "mailto:nicruo@gmail.com"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"